version: "3.9"

services:
  postgres:
    image: postgres
    container_name: awesome_links_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=awesome-links
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: